### PR TITLE
alerts-server: Add support for EOS, DAI and EURS on HitBTC

### PR DESCRIPTION
**Pull request by picimaci**
Added missing HitBTC markets (EOS, DAI and EURS) to code and tests. Solves #19 .

### CODE REVIEW

**Comment by AlexITC** [comment]
While the code looks good, I wonder if you have tried running the project to let the synchronization store the new markets.

**Comment by picimaci** [comment]
Now I have and there seems to be no warnings left considering missing markets.

**Comment by AlexITC** [comment]
Where the markets actually stored? A fast try didn't.

**Comment by AlexITC** [comment]
Probably HitBTC introduced breaking API changes that broke our client.

**Comment by AlexITC** [comment]
In fact, HitBTC returns nulls which we don't expect:
```
    {
        "ask": null, 
        "bid": "0.004321", 
        "high": "", 
        "last": null, 
        "low": "", 
        "open": null, 
        "symbol": "USCETH", 
        "timestamp": "2018-10-06T15:47:52.679Z", 
        "volume": "0", 
        "volumeQuote": "0.00000"
    },
```

That is causing the whole list to be ignored.

**Pull request merged**
